#项目启动端口
server:
  port: 8080

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chens.exam.wms.entity
  typeEnumsPackage: com.chens.exam.wms.enums