#项目启动端口
server:
  port: 8081


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chens.exam.core.entity; com.chens.bpm.entity
  typeEnumsPackage: com.chens.exam.core.enums; com.chens.bpm.enums
  global-config:
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    
#应用名称
spring:
  application:
    name: exam-wms
  #数据库连接
  datasource:
    url: jdbc:mysql://${chens_mysql_url:chens}:3306/qyexam?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: abc@123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false    #校验流程文件，默认校验resources下的processes文件夹里的流程文件 
    database-schema-update: true  #没有时自动创建表。有时不创建   
  devtools:
    restart:
      enabled: false #是否开启开发者工具

eureka:
  client:
    serviceUrl:
      defaultZone: ${chens_eureka_serviceUrl:http://127.0.0.1:8761/eureka/}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）

feign:
  httpclient:
    enabled: true