server:
  port: 8082
  context-path: /exam-web
  session:
    timeout: 600

spring:
  application:
    name: exam-web

eureka:
  client:
 #   register-with-eureka: false #不注册到注册中心，web模块只用于消费服务
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用IP地址
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000