server:
  port: 8082

spring:
  application:
    name: exam-web

eureka:
  client:
 #   register-with-eureka: false #不注册到注册中心，web模块只用于消费服务
    registry-fetch-interval-seconds: 10 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/ #注册中心地址
  instance:
    prefer-ip-address: true #使用IP地址

####################这里开始进入ZUUL配置###################################
zuul:
  # 代理普通http请求的超时时间
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 5000
    # http连接池大小
    maxTotalConnections: 200
    # 每个host最大连接数
    maxPerRouteConnections: 20
  # 开启重试
  retryable: true
  # 路径前面加一个前缀
  prefix: /api
  # 不代理某些服务，有些服务不对外公布，就可以在这里忽略掉
  # 比如sms-interface，我们不对外开放，可以在这里忽略掉，不然zuul从eureka获取到后就可以进行代理
  ignored-services:
  # hystrix 隔离策略，默认信号量(因为zuul中大量用到线程变量)。优先级要高过在hystrix中配置；
  ribbonIsolationStrategy: SEMAPHORE
  semaphore:
    # 信号量模式下，最大并发量。优先级要高过在hystrix中配置；
    maxSemaphores: 100

####################这里开始是路由配置###################################
# 通过配置文件配置的静态路由
routes:
  # 指定了一个路由，Id为uaa-token，在做验权的时候需要用到,back目前没发现实际意义，好像就是名字
  back:
    # 指定这个路径会匹配到这个路由。
    path: /admin/**
    # 这里表示，这个路由的实例信息，是通过ribbon负载均衡器进行获取的。值就是对应服务名
    serviceId: chens-admin-web

  auth:
    path: /exam-wms/**
    serviceId: exam-wms


####################结束路由配置###################################

####################这里开始是filter相关配置###################################
# 禁用springcloud自带的errorfilter
SendErrorFilter:
  error:
    disable: true
# 开启自定义的token校验filter
TokenValidateFilter:
  pre:
    disable: false
####################filter配置结束###################################


ribbon:
  # 配置ribbon默认的超时时间
  ConnectTimeout: 5000
  ReadTimeout: 5000
  # 是否开启重试
  OkToRetryOnAllOperations: true
  # 重试期间，实例切换次数
  MaxAutoRetriesNextServer: 3
  # 当前实例重试次数
  MaxAutoRetries: 0

########hystrix相关配置
hystrix:
  command:
    # 这是默认的配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 命令执行超时时间 20秒
            timeoutInMilliseconds: 20000

# 以下是自定义的配置，配置的值会被注入到TonyConfigurationBean这个类
tony:
  zuul:
    # 是否开启默认fallback
    defaultFallback:
      enable: false
    tokenFilter:
      noAuthenticationRoutes:
        - uaa-token